2021-02-07 14:30:43,783 ERROR: Exception on /login [GET] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 17, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2021-02-07 14:30:43,995 ERROR: Exception on /favicon.ico [GET] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 17, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
